### ISSUE TITLE
Script hangs when Internet connection is unstable

### ISSUE THREAD

**Issue by davinerd** [janiko71/aws-inventory#15]
When Internet connection is unstable, threads wait forever due to the missing timeout in the underline threading's `acquire` call (I suppose).

Specifying a timeout will ensure the script to ends at some point, writing the information gathered so far.

**Comment by janiko71** [comment]
Hi, thank you for your comment. I understand your point, but adding a timeout can be a bit tricky even if the script supports restarts. However, I will take a look.

**Comment by janiko71** [comment]
The script SHOULD NOT be executed with a bad or unstable network connection. There's a bunch of AWS API calls.
