### ISSUE TITLE
S3 inventory broken?

### ISSUE THREAD

**Issue by davinerd** [janiko71/aws-inventory#16]
```
ᐅ python inventory.py s3                                                                        
----------------------------------------------------------------------------------------------------
Number of services   : 1
Services List        : ['s3']
----------------------------------------------------------------------------------------------------

Traceback (most recent call last):! Region : global           ! s3 (list_buckets)                    
  File "inventory.py", line 449, in <module>
    inventory[svc] = config.global_inventory[svc]    
KeyError: 's3'
```

Note that the above error appears after editing line https://github.com/janiko71/aws-inventory/blob/master/inventory.py#L411 to `th.join(60)`

**Comment by janiko71** [comment]
Hi, sorry for the delay. Do you have more information about this error?

**Comment by davinerd** [comment]
The issue does not appear on a consistent base. I was able to reproduce it only few times, and based on that, I think the issue is here: https://github.com/janiko71/aws-inventory/blob/master/res/storage.py#L58

I think there is an uncaught exception that throw off the whole function.

Unfortunately cannot tell you more.

If it happens again, I'll add more details.

Thank you.
