### ISSUE TITLE
Fail when use parameters

### ISSUE THREAD

**Issue by marcos-wiris** [janiko71/aws-inventory#25]
Hi
I'm checking script with parameters profile and services how appears in the wiki but appears error for parameters. 

`Exception: Unknown argument [--profile]`
`Exception: Unknown argument [--services]`

simply I execute 

python3 inventory.py --profile tools --services ec2

Which config is missing?

**Comment by janiko71** [comment]
Hi, I'm updating the project, but the dev branch has not been merged yet, and the wiki shows the new arguments. Try to get the dev branch with `git clone -b dev ...`. It should work better ;)

**Comment by marcos-wiris** [comment]
Cool! Thanks :+1:
