### ISSUE TITLE
Not (yet) Running from CloudShell (AWS or GCP)

### ISSUE THREAD

**Issue by jwdinkel** [janiko71/aws-inventory#30]
Has anybody tried this on [Google Cloud Shell](https://shell.cloud.google.com/?show=ide%2Cterminal) or in AWS CloudShell?

I use the following commands to start the project:

- git clone https://github.com/janiko71/aws-inventory.git
- cd aws-inventory
- pip3 install -r requirements.txt
- python3 inventory.py

pip3 install gives some errors on AWS Cloudshell, but works fine on GCP.

However, both CloudShells leave me with a non-working application:

I get this error:
`Traceback (most recent call last):
  File "inventory.py", line 61, in <module>
    ownerId = utils.get_ownerID(profile_name)
  File "/home/jason_dinkel/729121273778/aws-inventory/res/utils.py", line 173, in get_ownerID
    identity = sts.get_caller_identity()
  File "/home/jason_dinkel/.local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/jason_dinkel/.local/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired`

Now, the token comes from the SSO console for GCP and for AWS, the credentials are built-into the cloudshell, so neither should be the problem.

Also, the AWS Cloudshell shouldn't prompt for a [default] profile.
`[cloudshell-user@ip-10-0-28-32 aws-inventory]$ python3 inventory.py`
`Profile name [default] not found, please check.`

If anybody wants to have a look, I'd appreciate it. If I find a solution, I will post the steps.

Thanks.

**Comment by janiko71** [comment]
Hi,
I think I get the point. At the time of writing this program, CloudShell didn't exist. So the only solution to execute the program was to use the user's session (with one of the profiles created with the `aws configure` command). In that case, at least one profile is created (and named). I will try some trick that could work in a CloudShell environment, where no default profile is present. 
To check, try the dev branch: `git -b dev https://github.com/janiko71/aws-inventory.git`

**Comment by um-freiberg** [comment]
Hi, I'm also interested in this. I've tried running the dev branch in a fresh AWS CloudShell

```
[cloudshell-user@ip-10-0-12-2 aws-inventory]$ python ./inventory.py 
Traceback (most recent call last):
  File "./inventory.py", line 2, in <module>
    import boto3
ImportError: No module named boto3
```

According to AWS boto3 should come pre-installed: https://docs.aws.amazon.com/cloudshell/latest/userguide/vm-specs.html#pre-installed-software

```
[cloudshell-user@ip-10-0-12-2 aws-inventory]$ pip3 install --user boto3
Requirement already satisfied: boto3 in /usr/local/lib/python3.7/site-packages
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /usr/local/lib/python3.7/site-packages (from boto3)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.7/site-packages (from boto3)
Requirement already satisfied: botocore<1.18.0,>=1.17.63 in /usr/local/lib/python3.7/site-packages (from boto3)
Requirement already satisfied: urllib3<1.26,>=1.20; python_version != "3.4" in /usr/local/lib/python3.7/site-packages (from botocore<1.18.0,>=1.17.63->boto3)
Requirement already satisfied: docutils<0.16,>=0.10 in /usr/local/lib/python3.7/site-packages (from botocore<1.18.0,>=1.17.63->boto3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.7/site-packages (from botocore<1.18.0,>=1.17.63->boto3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.18.0,>=1.17.63->boto3)
```

**Comment by um-freiberg** [comment]
Adding to my previous comment, could it be that the AWS region is not set?

```
[cloudshell-user@ip-10-0-12-2 aws-inventory]$ python3 ./inventory.py --log debug
---
Traceback (most recent call last):
  File "./inventory.py", line 68, in <module>
    config.regions = utils.get_aws_regions(profile_name)
  File "/home/cloudshell-user/aws-inventory/res/utils.py", line 51, in get_aws_regions
    current_zones = client.describe_availability_zones()
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnauthorizedOperation) when calling the DescribeAvailabilityZones operation: You are not authorized to perform this operation.
```

**Comment by janiko71** [comment]
To run inventory, your user needs to have the good IAM rights (at least the ones in the `inventory-policy-*.json`).

More suprising, when I test in CloudShell, it works sometimes, but it fails sometimes too with a Timeout error. Don't know the root cause yet.

**Comment by um-freiberg** [comment]
I tried in an account where I have full admin permissions. Initially it started going through the regions but failed at some point. On subsequent invocations, it fails with an ECS related error even when limiting the service to S3 for example.

```
[cloudshell-user@ip-10-0-151-147 aws-inventory]$ python3 ./inventory.py  --services s3
----------------------------------------------------------------------------------------------------
Number of services   : 1
Services List        : ['s3']
----------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1863, in fetch_creds
    full_uri, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/botocore/utils.py", line 2069, in retrieve_full_uri
    return self._retrieve_credentials(full_url, headers)
  File "/usr/local/lib/python3.7/site-packages/botocore/utils.py", line 2106, in _retrieve_credentials
    full_url, headers, self.TIMEOUT_SECONDS)
  File "/usr/local/lib/python3.7/site-packages/botocore/utils.py", line 2125, in _get_response
    ) % (response.status_code, response_text))
botocore.exceptions.MetadataRetrievalError: Error retrieving metadata: Received non 200 response (503) from ECS metadata: <html><head><title>Timeout</title></head><body><h1>Timeout</h1></body></html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./inventory.py", line 61, in <module>
    ownerId = utils.get_ownerID(profile_name)
  File "/home/cloudshell-user/aws-inventory/res/utils.py", line 176, in get_ownerID
    sts = session.client('sts')
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 826, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 431, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1969, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1832, in load
    return self._retrieve_or_fail()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1841, in _retrieve_or_fail
    creds = fetcher()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1868, in fetch_creds
    error_msg=str(e))
botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from container-role: Error retrieving metadata: Received non 200 response (503) from ECS metadata: <html><head><title>Timeout</title></head><body><h1>Timeout</h1></body></html>
```

**Comment by janiko71** [comment]
I saw that. CloudShell definitively doesn't work like a simple API call. Maybe there's something different with some [parameters](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials), I think network delay is higher, or maybe we need a bigger TIMEOUT or more retries. Don't know yet if I can change this (and where...).

**Comment by toninog** [comment]
I have the same issue - tracked it down to the script not collecting credentials from ENV - in cloudShell it uses STS to provide credentials - so you usually have no ~/.aws/credentials file - and more 

AWS_ACCESS_KEY_ID=asdasdasdasdasdasdasdasd
AWS_REGION=eu-west-1
AWS_SECRET_ACCESS_KEY=asdasdasdasdasd
AWS_SESSION_TOKEN=longer_sdsdssfsdfsdfsdf

Is there an option to add support for pulling credentials from local ENV?

**Comment by toninog** [comment]
I did some more work on this and found the following works for me - the real issue is how do you decide which part to use: Profile or ENV?

```
diff --git a/res/glob.py b/res/glob.py
index 5fa96d0..8084ca9 100644
--- a/res/glob.py
+++ b/res/glob.py
@@ -74,7 +74,8 @@ def get_inventory(ownerId,
                 utils.progress(region_name)
                 config.logger.info('Account {}, {} inventory for region {}'.format(ownerId, aws_service, region_name))

-                session = boto3.Session(profile_name=profile)
+                # session = boto3.Session(profile_name=profile)
+                session = boto3.session.Session()
                 client = session.client(aws_service, region_name)

                 if (pagination):
diff --git a/res/utils.py b/res/utils.py
index 408ecb9..6a71e18 100644
--- a/res/utils.py
+++ b/res/utils.py
@@ -32,7 +32,9 @@ def get_aws_regions(profile_name):

     # We get the regions list through EC2.

-    session = boto3.Session(profile_name=profile_name, region_name="us-east-1")
+    #session = boto3.Session(profile_name=profile_name, region_name="us-east-1")
+    session = boto3.session.Session()
+
     client = session.client("ec2")

     regions = client.describe_regions(AllRegions=True)
@@ -46,7 +48,8 @@ def get_aws_regions(profile_name):
         # Looking for AZ? Why not? But only if you have the rights to...
         current_region = region['RegionName']
         if (region['OptInStatus'] != 'not-opted-in'):
-            session = boto3.Session(profile_name=profile_name)
+            #session = boto3.Session(profile_name=profile_name)
+            session = boto3.session.Session()
             client = session.client("ec2", region_name=current_region)
             current_zones = client.describe_availability_zones()
             region['zones'] = current_zones['AvailabilityZones']
@@ -209,4 +212,4 @@ def json_datetime_converter(json_text):
 # Hey, doc: we're in a module!
 #
 if (__name__ == '__main__'):
-    print('Module => Do not execute')
\ No newline at end of file
+    print('Module => Do not execute')
```

**Comment by janiko71** [comment]
Hi, can you check if it works better with the dev branch?

**Comment by toninog** [comment]
Yup - all good from AWS CloudShell as well as bash CLI using STS and ENV credentials

Thanks !

**Comment by janiko71** [comment]
You're welcome!

**Comment by janiko71** [comment]
Looks good, PR to main done.
